volumes:
  postgres-data:
  postgres-config:
  pgadmin:
  api-dev-files:
  api-public:
  api-bin:
  api-tmp:
  caddy-config:
  caddy-data:

services:
  caddy:
    image: caddy:2.11-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8.35
    # ports:
    #   - "3000:3000"
    command:
      - "gotenberg"
      - "--chromium-clear-cache=true"
      - "--chromium-auto-start=true"

  db:
    platform: linux/amd64
    image: postgres:18.4
    volumes:
      - postgres-data:/var/lib/postgresql
      - postgres-config:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      PGUSER: ${DB_USER}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"] # For Dev only!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:9.17
    depends_on:
      - db
    # ports:
    #   - "5430:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PW}
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    restart: unless-stopped

  api-dev:
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./assets:/opt/app/assets
      - ./cmd:/opt/app/cmd
      - ./docs:/opt/app/docs
      - ./internal:/opt/app/internal
      - ./pkg:/opt/app/pkg
      - ./sqlc:/opt/app/sqlc
      - api-dev-files:/opt/app/files
      - api-public:/opt/app/public
      - api-bin:/opt/app/bin
      - api-tmp:/opt/app/tmp
    # ports:
    #   - 8081:8080
    #   - 8090:8090
    env_file: ".env"
    depends_on:
      gotenberg:
        condition: service_started
      caddy:
        condition: service_started
      db:
        condition: service_healthy

  api:
    build:
      dockerfile: Dockerfile
      context: ./
      target: prod
    develop:
      watch:
        - action: rebuild
          path: ./internal # Watch this directory
    env_file: ".env"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2048M
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - api-dev-files:/opt/app/files
    depends_on:
      gotenberg:
        condition: service_started
      db:
        condition: service_healthy
