// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_queue.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextEmailQueueEntry = `-- name: ClaimNextEmailQueueEntry :one
UPDATE email_queue
SET status = 'sending', updated_at = now()
WHERE uuid = (
  SELECT uuid FROM email_queue
  WHERE status IN ('pending', 'failed')
    AND next_attempt_at <= now()
    AND attempts < max_attempts
  ORDER BY created_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
) RETURNING uuid, to_addresses, cc_addresses, bcc_addresses, subject, body, attachments, status, attempts, max_attempts, next_attempt_at, last_error, created_at, updated_at, sent_at
`

func (q *Queries) ClaimNextEmailQueueEntry(ctx context.Context) (EmailQueue, error) {
	row := q.db.QueryRow(ctx, claimNextEmailQueueEntry)
	var i EmailQueue
	err := row.Scan(
		&i.Uuid,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Attachments,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const createEmailQueueEntry = `-- name: CreateEmailQueueEntry :one
INSERT INTO email_queue (
  to_addresses,
  cc_addresses,
  bcc_addresses,
  subject,
  body,
  attachments,
  max_attempts
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
) RETURNING uuid, to_addresses, cc_addresses, bcc_addresses, subject, body, attachments, status, attempts, max_attempts, next_attempt_at, last_error, created_at, updated_at, sent_at
`

type CreateEmailQueueEntryParams struct {
	ToAddresses  []string `json:"to_addresses"`
	CcAddresses  []string `json:"cc_addresses"`
	BccAddresses []string `json:"bcc_addresses"`
	Subject      string   `json:"subject"`
	Body         string   `json:"body"`
	Attachments  []string `json:"attachments"`
	MaxAttempts  int32    `json:"max_attempts"`
}

func (q *Queries) CreateEmailQueueEntry(ctx context.Context, arg CreateEmailQueueEntryParams) (EmailQueue, error) {
	row := q.db.QueryRow(ctx, createEmailQueueEntry,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.Body,
		arg.Attachments,
		arg.MaxAttempts,
	)
	var i EmailQueue
	err := row.Scan(
		&i.Uuid,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Attachments,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const deleteEmailQueueEntry = `-- name: DeleteEmailQueueEntry :exec
DELETE FROM email_queue
WHERE uuid = $1
`

func (q *Queries) DeleteEmailQueueEntry(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailQueueEntry, argUuid)
	return err
}

const getEmailQueueEntries = `-- name: GetEmailQueueEntries :many
SELECT uuid, to_addresses, cc_addresses, bcc_addresses, subject, body, attachments, status, attempts, max_attempts, next_attempt_at, last_error, created_at, updated_at, sent_at FROM email_queue
ORDER BY created_at DESC
LIMIT 200
`

func (q *Queries) GetEmailQueueEntries(ctx context.Context) ([]EmailQueue, error) {
	rows, err := q.db.Query(ctx, getEmailQueueEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailQueue{}
	for rows.Next() {
		var i EmailQueue
		if err := rows.Scan(
			&i.Uuid,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.Body,
			&i.Attachments,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailQueueFailed = `-- name: MarkEmailQueueFailed :exec
UPDATE email_queue
SET status = CASE WHEN attempts + 1 >= max_attempts THEN 'dead' ELSE 'failed' END,
    attempts = attempts + 1,
    next_attempt_at = now() + make_interval(secs => $2),
    last_error = $3,
    updated_at = now()
WHERE uuid = $1
`

type MarkEmailQueueFailedParams struct {
	Uuid      uuid.UUID   `json:"uuid"`
	Secs      float64     `json:"secs"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEmailQueueFailed(ctx context.Context, arg MarkEmailQueueFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailQueueFailed, arg.Uuid, arg.Secs, arg.LastError)
	return err
}

const markEmailQueueSent = `-- name: MarkEmailQueueSent :exec
UPDATE email_queue
SET status = 'sent', sent_at = now(), updated_at = now(), last_error = NULL
WHERE uuid = $1
`

func (q *Queries) MarkEmailQueueSent(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailQueueSent, argUuid)
	return err
}

const resetEmailQueueEntry = `-- name: ResetEmailQueueEntry :exec
UPDATE email_queue
SET status = 'pending', attempts = 0, next_attempt_at = now(),
    last_error = NULL, updated_at = now()
WHERE uuid = $1
`

func (q *Queries) ResetEmailQueueEntry(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetEmailQueueEntry, argUuid)
	return err
}
