// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: obmann.sql

package sqlc

import (
	"context"

	"github.com/bata94/RegattaApi/pkg/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createObmann = `-- name: CreateObmann :one
INSERT INTO obmann (
  uuid,
  verein_uuid,
  name,
  email,
  phone
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING uuid, name, email, phone, verein_uuid
`

type CreateObmannParams struct {
	Uuid       uuid.UUID   `json:"uuid"`
	VereinUuid uuid.UUID   `json:"verein_uuid"`
	Name       pgtype.Text `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
}

func (q *Queries) CreateObmann(ctx context.Context, arg CreateObmannParams) (Obmann, error) {
	row := q.db.QueryRow(ctx, createObmann,
		arg.Uuid,
		arg.VereinUuid,
		arg.Name,
		arg.Email,
		arg.Phone,
	)
	var i Obmann
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VereinUuid,
	)
	return i, err
}

const deleteObmann = `-- name: DeleteObmann :exec
DELETE FROM obmann
WHERE uuid = $1
`

func (q *Queries) DeleteObmann(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteObmann, argUuid)
	return err
}

const getAllObmann = `-- name: GetAllObmann :many
SELECT uuid, name, email, phone, verein_uuid FROM obmann
ORDER BY name ASC
`

func (q *Queries) GetAllObmann(ctx context.Context) ([]Obmann, error) {
	rows, err := q.db.Query(ctx, getAllObmann)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Obmann{}
	for rows.Next() {
		var i Obmann
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.VereinUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllObmannForVerein = `-- name: GetAllObmannForVerein :many
SELECT uuid, name, email, phone, verein_uuid FROM obmann
WHERE verein_uuid = $1
ORDER BY name ASC
`

func (q *Queries) GetAllObmannForVerein(ctx context.Context, vereinUuid uuid.UUID) ([]Obmann, error) {
	rows, err := q.db.Query(ctx, getAllObmannForVerein, vereinUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Obmann{}
	for rows.Next() {
		var i Obmann
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.VereinUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObmannMinimal = `-- name: GetObmannMinimal :one
SELECT uuid, name, email, phone, verein_uuid FROM obmann
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetObmannMinimal(ctx context.Context, argUuid uuid.UUID) (Obmann, error) {
	row := q.db.QueryRow(ctx, getObmannMinimal, argUuid)
	var i Obmann
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VereinUuid,
	)
	return i, err
}

const updateObmann = `-- name: UpdateObmann :one
UPDATE obmann
SET
  name = $2,
  email = $3,
  phone = $4,
  verein_uuid = $5
WHERE uuid = $1
RETURNING uuid, name, email, phone, verein_uuid
`

type UpdateObmannParams struct {
	Uuid       uuid.UUID   `json:"uuid"`
	Name       pgtype.Text `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	VereinUuid uuid.UUID   `json:"verein_uuid"`
}

func (q *Queries) UpdateObmann(ctx context.Context, arg UpdateObmannParams) (Obmann, error) {
	row := q.db.QueryRow(ctx, updateObmann,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.VereinUuid,
	)
	var i Obmann
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VereinUuid,
	)
	return i, err
}
