// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: startnummern_bereich.sql

package sqlc

import (
	"context"
)

const getStartnummernBereich = `-- name: GetStartnummernBereich :one
SELECT id, min_nummer, max_nummer, fehlende_nummern FROM startnummern_bereich
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetStartnummernBereich(ctx context.Context) (StartnummernBereich, error) {
	row := q.db.QueryRow(ctx, getStartnummernBereich)
	var i StartnummernBereich
	err := row.Scan(
		&i.ID,
		&i.MinNummer,
		&i.MaxNummer,
		&i.FehlendeNummern,
	)
	return i, err
}

const setStartnummernBereich = `-- name: SetStartnummernBereich :one
INSERT INTO startnummern_bereich (
  id,
  min_nummer,
  max_nummer,
  fehlende_nummern
) VALUES (
  1, $1, $2, $3
)
ON CONFLICT (id) DO UPDATE
SET
  min_nummer = EXCLUDED.min_nummer,
  max_nummer = EXCLUDED.max_nummer,
  fehlende_nummern = EXCLUDED.fehlende_nummern
RETURNING id, min_nummer, max_nummer, fehlende_nummern
`

type SetStartnummernBereichParams struct {
	MinNummer       int32   `json:"min_nummer"`
	MaxNummer       int32   `json:"max_nummer"`
	FehlendeNummern []int32 `json:"fehlende_nummern"`
}

func (q *Queries) SetStartnummernBereich(ctx context.Context, arg SetStartnummernBereichParams) (StartnummernBereich, error) {
	row := q.db.QueryRow(ctx, setStartnummernBereich, arg.MinNummer, arg.MaxNummer, arg.FehlendeNummern)
	var i StartnummernBereich
	err := row.Scan(
		&i.ID,
		&i.MinNummer,
		&i.MaxNummer,
		&i.FehlendeNummern,
	)
	return i, err
}
