// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  group_uuid,
  username,
  hashed_password,
  uuid
) VALUES (
  $1, $2, $3, gen_random_uuid()
)
RETURNING ulid, username, hashed_password, is_active, group_uuid, uuid
`

type CreateUserParams struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.GroupUuid, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.Ulid,
		&i.Username,
		&i.HashedPassword,
		&i.IsActive,
		&i.GroupUuid,
		&i.Uuid,
	)
	return i, err
}

const getAllUser = `-- name: GetAllUser :many
SELECT ulid, username, hashed_password, is_active, group_uuid, uuid FROM users
ORDER BY uuid
`

func (q *Queries) GetAllUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Ulid,
			&i.Username,
			&i.HashedPassword,
			&i.IsActive,
			&i.GroupUuid,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT users.ulid, users.username, users.hashed_password, users.is_active, users.group_uuid, users.uuid, users_group.ulid, users_group.name, users_group.allowed_admin, users_group.allowed_zeitnahme, users_group.allowed_startlisten, users_group.allowed_regattaleitung, users_group.uuid
FROM users
JOIN users_group
ON users.group_uuid = users_group.uuid
WHERE users.uuid = $1 LIMIT 1
`

type GetUserRow struct {
	User       User       `json:"user"`
	UsersGroup UsersGroup `json:"users_group"`
}

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, argUuid)
	var i GetUserRow
	err := row.Scan(
		&i.User.Ulid,
		&i.User.Username,
		&i.User.HashedPassword,
		&i.User.IsActive,
		&i.User.GroupUuid,
		&i.User.Uuid,
		&i.UsersGroup.Ulid,
		&i.UsersGroup.Name,
		&i.UsersGroup.AllowedAdmin,
		&i.UsersGroup.AllowedZeitnahme,
		&i.UsersGroup.AllowedStartlisten,
		&i.UsersGroup.AllowedRegattaleitung,
		&i.UsersGroup.Uuid,
	)
	return i, err
}

const getUserMinimal = `-- name: GetUserMinimal :one
SELECT ulid, username, hashed_password, is_active, group_uuid, uuid FROM users
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUserMinimal(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserMinimal, argUuid)
	var i User
	err := row.Scan(
		&i.Ulid,
		&i.Username,
		&i.HashedPassword,
		&i.IsActive,
		&i.GroupUuid,
		&i.Uuid,
	)
	return i, err
}

const getUserUuidByName = `-- name: GetUserUuidByName :one
SELECT uuid
FROM users
WHERE username = $1
`

func (q *Queries) GetUserUuidByName(ctx context.Context, username string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserUuidByName, username)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}
