// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_group.sql

package sqlc

import (
	"context"

	"github.com/bata94/RegattaApi/pkg/uuid"
)

const createUserGroup = `-- name: CreateUserGroup :one
INSERT INTO users_group (
  name,
  capabilities,
  uuid
) VALUES (
  $1, $2, uuidv7()
)
RETURNING uuid, name, capabilities
`

type CreateUserGroupParams struct {
	Name         string           `json:"name"`
	Capabilities []UserCapability `json:"capabilities"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UsersGroup, error) {
	row := q.db.QueryRow(ctx, createUserGroup, arg.Name, arg.Capabilities)
	var i UsersGroup
	err := row.Scan(&i.Uuid, &i.Name, &i.Capabilities)
	return i, err
}

const getAllUserGroup = `-- name: GetAllUserGroup :many
SELECT uuid, name, capabilities FROM users_group
ORDER BY uuid
`

func (q *Queries) GetAllUserGroup(ctx context.Context) ([]UsersGroup, error) {
	rows, err := q.db.Query(ctx, getAllUserGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersGroup{}
	for rows.Next() {
		var i UsersGroup
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroup = `-- name: GetUserGroup :many
SELECT users_group.uuid, users_group.name, users_group.capabilities, users.uuid, users.username, users.hashed_password, users.is_active, users.group_uuid
FROM users_group
JOIN users
ON users_group.uuid = users.group_uuid
WHERE users_group.uuid = $1
`

type GetUserGroupRow struct {
	UsersGroup UsersGroup `json:"users_group"`
	User       User       `json:"user"`
}

func (q *Queries) GetUserGroup(ctx context.Context, argUuid uuid.UUID) ([]GetUserGroupRow, error) {
	rows, err := q.db.Query(ctx, getUserGroup, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupRow{}
	for rows.Next() {
		var i GetUserGroupRow
		if err := rows.Scan(
			&i.UsersGroup.Uuid,
			&i.UsersGroup.Name,
			&i.UsersGroup.Capabilities,
			&i.User.Uuid,
			&i.User.Username,
			&i.User.HashedPassword,
			&i.User.IsActive,
			&i.User.GroupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupMinimal = `-- name: GetUserGroupMinimal :one
SELECT uuid, name, capabilities
FROM users_group
WHERE users_group.uuid = $1
`

func (q *Queries) GetUserGroupMinimal(ctx context.Context, argUuid uuid.UUID) (UsersGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroupMinimal, argUuid)
	var i UsersGroup
	err := row.Scan(&i.Uuid, &i.Name, &i.Capabilities)
	return i, err
}

const getUserGroupUuidByName = `-- name: GetUserGroupUuidByName :one
SELECT uuid
FROM users_group
WHERE name = $1
`

func (q *Queries) GetUserGroupUuidByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserGroupUuidByName, name)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const updateUserGroup = `-- name: UpdateUserGroup :exec
UPDATE users_group
SET
  name = $2,
  capabilities = $3
WHERE uuid = $1
`

type UpdateUserGroupParams struct {
	Uuid         uuid.UUID        `json:"uuid"`
	Name         string           `json:"name"`
	Capabilities []UserCapability `json:"capabilities"`
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error {
	_, err := q.db.Exec(ctx, updateUserGroup, arg.Uuid, arg.Name, arg.Capabilities)
	return err
}
