// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/bata94/RegattaApi/pkg/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  group_uuid,
  username,
  hashed_password,
  is_active,
  uuid
) VALUES (
  $1, $2, $3, true, uuidv7()
)
RETURNING uuid, username, hashed_password, is_active, group_uuid
`

type CreateUserParams struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.GroupUuid, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.IsActive,
		&i.GroupUuid,
	)
	return i, err
}

const getAllUser = `-- name: GetAllUser :many
SELECT uuid, username, hashed_password, is_active, group_uuid FROM users
ORDER BY uuid
`

func (q *Queries) GetAllUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.HashedPassword,
			&i.IsActive,
			&i.GroupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT users.uuid, users.username, users.hashed_password, users.is_active, users.group_uuid, users_group.uuid, users_group.name, users_group.capabilities
FROM users
JOIN users_group
ON users.group_uuid = users_group.uuid
WHERE users.uuid = $1 LIMIT 1
`

type GetUserRow struct {
	User       User       `json:"user"`
	UsersGroup UsersGroup `json:"users_group"`
}

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, argUuid)
	var i GetUserRow
	err := row.Scan(
		&i.User.Uuid,
		&i.User.Username,
		&i.User.HashedPassword,
		&i.User.IsActive,
		&i.User.GroupUuid,
		&i.UsersGroup.Uuid,
		&i.UsersGroup.Name,
		&i.UsersGroup.Capabilities,
	)
	return i, err
}

const getUserMinimal = `-- name: GetUserMinimal :one
SELECT uuid, username, hashed_password, is_active, group_uuid FROM users
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUserMinimal(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserMinimal, argUuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.IsActive,
		&i.GroupUuid,
	)
	return i, err
}

const getUserUuidByName = `-- name: GetUserUuidByName :one
SELECT uuid
FROM users
WHERE username = $1
`

func (q *Queries) GetUserUuidByName(ctx context.Context, username string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserUuidByName, username)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET
  hashed_password = $2
WHERE uuid = $1
`

type UpdatePasswordParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Uuid, arg.HashedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  username = $2,
  is_active = $3,
  group_uuid = $4
WHERE uuid = $1
`

type UpdateUserParams struct {
	Uuid      uuid.UUID `json:"uuid"`
	Username  string    `json:"username"`
	IsActive  bool      `json:"is_active"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Uuid,
		arg.Username,
		arg.IsActive,
		arg.GroupUuid,
	)
	return err
}
