// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_group.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUserGroup = `-- name: CreateUserGroup :one
INSERT INTO users_group (
  name,
  allowed_admin,
  allowed_zeitnahme,
  allowed_startlisten,
  allowed_regattabuero,
  allowed_regattaleitung,
  uuid
) VALUES (
  $1, $2, $3, $4, $5, $6, uuidv7()
)
RETURNING uuid, name, allowed_admin, allowed_zeitnahme, allowed_startlisten, allowed_regattabuero, allowed_regattaleitung
`

type CreateUserGroupParams struct {
	Name                  string `json:"name"`
	AllowedAdmin          bool   `json:"allowed_admin"`
	AllowedZeitnahme      bool   `json:"allowed_zeitnahme"`
	AllowedStartlisten    bool   `json:"allowed_startlisten"`
	AllowedRegattabuero   bool   `json:"allowed_regattabuero"`
	AllowedRegattaleitung bool   `json:"allowed_regattaleitung"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UsersGroup, error) {
	row := q.db.QueryRow(ctx, createUserGroup,
		arg.Name,
		arg.AllowedAdmin,
		arg.AllowedZeitnahme,
		arg.AllowedStartlisten,
		arg.AllowedRegattabuero,
		arg.AllowedRegattaleitung,
	)
	var i UsersGroup
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.AllowedAdmin,
		&i.AllowedZeitnahme,
		&i.AllowedStartlisten,
		&i.AllowedRegattabuero,
		&i.AllowedRegattaleitung,
	)
	return i, err
}

const getAllUserGroup = `-- name: GetAllUserGroup :many
SELECT uuid, name, allowed_admin, allowed_zeitnahme, allowed_startlisten, allowed_regattabuero, allowed_regattaleitung FROM users_group
ORDER BY uuid
`

func (q *Queries) GetAllUserGroup(ctx context.Context) ([]UsersGroup, error) {
	rows, err := q.db.Query(ctx, getAllUserGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersGroup{}
	for rows.Next() {
		var i UsersGroup
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.AllowedAdmin,
			&i.AllowedZeitnahme,
			&i.AllowedStartlisten,
			&i.AllowedRegattabuero,
			&i.AllowedRegattaleitung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroup = `-- name: GetUserGroup :many
SELECT users_group.uuid, users_group.name, users_group.allowed_admin, users_group.allowed_zeitnahme, users_group.allowed_startlisten, users_group.allowed_regattabuero, users_group.allowed_regattaleitung, users.uuid, users.username, users.hashed_password, users.is_active, users.group_uuid
FROM users_group
JOIN users
ON users_group.uuid = users.group_uuid
WHERE users_group.uuid = $1
`

type GetUserGroupRow struct {
	UsersGroup UsersGroup `json:"users_group"`
	User       User       `json:"user"`
}

func (q *Queries) GetUserGroup(ctx context.Context, argUuid uuid.UUID) ([]GetUserGroupRow, error) {
	rows, err := q.db.Query(ctx, getUserGroup, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupRow{}
	for rows.Next() {
		var i GetUserGroupRow
		if err := rows.Scan(
			&i.UsersGroup.Uuid,
			&i.UsersGroup.Name,
			&i.UsersGroup.AllowedAdmin,
			&i.UsersGroup.AllowedZeitnahme,
			&i.UsersGroup.AllowedStartlisten,
			&i.UsersGroup.AllowedRegattabuero,
			&i.UsersGroup.AllowedRegattaleitung,
			&i.User.Uuid,
			&i.User.Username,
			&i.User.HashedPassword,
			&i.User.IsActive,
			&i.User.GroupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupMinimal = `-- name: GetUserGroupMinimal :one
SELECT uuid, name, allowed_admin, allowed_zeitnahme, allowed_startlisten, allowed_regattabuero, allowed_regattaleitung
FROM users_group
WHERE users_group.uuid = $1
`

func (q *Queries) GetUserGroupMinimal(ctx context.Context, argUuid uuid.UUID) (UsersGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroupMinimal, argUuid)
	var i UsersGroup
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.AllowedAdmin,
		&i.AllowedZeitnahme,
		&i.AllowedStartlisten,
		&i.AllowedRegattabuero,
		&i.AllowedRegattaleitung,
	)
	return i, err
}

const getUserGroupUuidByName = `-- name: GetUserGroupUuidByName :one
SELECT uuid
FROM users_group
WHERE name = $1
`

func (q *Queries) GetUserGroupUuidByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserGroupUuidByName, name)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const updateUserGroup = `-- name: UpdateUserGroup :exec
UPDATE users_group
SET
  name = $2,
  allowed_admin = $3,
  allowed_zeitnahme = $4,
  allowed_startlisten = $5,
  allowed_regattabuero = $6,
  allowed_regattaleitung = $7
WHERE uuid = $1
`

type UpdateUserGroupParams struct {
	Uuid                  uuid.UUID `json:"uuid"`
	Name                  string    `json:"name"`
	AllowedAdmin          bool      `json:"allowed_admin"`
	AllowedZeitnahme      bool      `json:"allowed_zeitnahme"`
	AllowedStartlisten    bool      `json:"allowed_startlisten"`
	AllowedRegattabuero   bool      `json:"allowed_regattabuero"`
	AllowedRegattaleitung bool      `json:"allowed_regattaleitung"`
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error {
	_, err := q.db.Exec(ctx, updateUserGroup,
		arg.Uuid,
		arg.Name,
		arg.AllowedAdmin,
		arg.AllowedZeitnahme,
		arg.AllowedStartlisten,
		arg.AllowedRegattabuero,
		arg.AllowedRegattaleitung,
	)
	return err
}
