// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verein.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVerein = `-- name: CreateVerein :one
INSERT INTO verein (
  uuid,
  name,
  kurzform,
  kuerzel
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING uuid, name, kurzform, kuerzel
`

type CreateVereinParams struct {
	Uuid     uuid.UUID `json:"uuid"`
	Name     string    `json:"name"`
	Kurzform string    `json:"kurzform"`
	Kuerzel  string    `json:"kuerzel"`
}

func (q *Queries) CreateVerein(ctx context.Context, arg CreateVereinParams) (Verein, error) {
	row := q.db.QueryRow(ctx, createVerein,
		arg.Uuid,
		arg.Name,
		arg.Kurzform,
		arg.Kuerzel,
	)
	var i Verein
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Kurzform,
		&i.Kuerzel,
	)
	return i, err
}

const getAllVerein = `-- name: GetAllVerein :many
SELECT uuid, name, kurzform, kuerzel FROM verein
ORDER BY name ASC
`

func (q *Queries) GetAllVerein(ctx context.Context) ([]Verein, error) {
	rows, err := q.db.Query(ctx, getAllVerein)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verein{}
	for rows.Next() {
		var i Verein
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Kurzform,
			&i.Kuerzel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVereinMinimal = `-- name: GetVereinMinimal :one
SELECT uuid, name, kurzform, kuerzel FROM verein
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetVereinMinimal(ctx context.Context, argUuid uuid.UUID) (Verein, error) {
	row := q.db.QueryRow(ctx, getVereinMinimal, argUuid)
	var i Verein
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Kurzform,
		&i.Kuerzel,
	)
	return i, err
}
