// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zeitnahme_start.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createZeitnahmeStart = `-- name: CreateZeitnahmeStart :one
INSERT INTO zeitnahme_start (
  rennen_nummer,
  start_nummer,
  time_client,
  time_server,
  measured_latency,
  client_id,
  seq
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, rennen_nummer, start_nummer, time_client, time_server, measured_latency, verarbeitet, client_id, seq
`

type CreateZeitnahmeStartParams struct {
	RennenNummer    pgtype.Text      `json:"rennen_nummer"`
	StartNummer     pgtype.Text      `json:"start_nummer"`
	TimeClient      pgtype.Timestamp `json:"time_client"`
	TimeServer      pgtype.Timestamp `json:"time_server"`
	MeasuredLatency pgtype.Int4      `json:"measured_latency"`
	ClientID        pgtype.Text      `json:"client_id"`
	Seq             pgtype.Text      `json:"seq"`
}

func (q *Queries) CreateZeitnahmeStart(ctx context.Context, arg CreateZeitnahmeStartParams) (ZeitnahmeStart, error) {
	row := q.db.QueryRow(ctx, createZeitnahmeStart,
		arg.RennenNummer,
		arg.StartNummer,
		arg.TimeClient,
		arg.TimeServer,
		arg.MeasuredLatency,
		arg.ClientID,
		arg.Seq,
	)
	var i ZeitnahmeStart
	err := row.Scan(
		&i.ID,
		&i.RennenNummer,
		&i.StartNummer,
		&i.TimeClient,
		&i.TimeServer,
		&i.MeasuredLatency,
		&i.Verarbeitet,
		&i.ClientID,
		&i.Seq,
	)
	return i, err
}

const deleteZeitnahmeStart = `-- name: DeleteZeitnahmeStart :exec
DELETE FROM zeitnahme_start
WHERE id = $1
`

func (q *Queries) DeleteZeitnahmeStart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteZeitnahmeStart, id)
	return err
}

const findZeitnahmeStartByClientSeq = `-- name: FindZeitnahmeStartByClientSeq :one
SELECT id, rennen_nummer, start_nummer, time_client, time_server, measured_latency, verarbeitet, client_id, seq FROM zeitnahme_start
WHERE client_id = $1 AND seq = $2
LIMIT 1
`

type FindZeitnahmeStartByClientSeqParams struct {
	ClientID pgtype.Text `json:"client_id"`
	Seq      pgtype.Text `json:"seq"`
}

func (q *Queries) FindZeitnahmeStartByClientSeq(ctx context.Context, arg FindZeitnahmeStartByClientSeqParams) (ZeitnahmeStart, error) {
	row := q.db.QueryRow(ctx, findZeitnahmeStartByClientSeq, arg.ClientID, arg.Seq)
	var i ZeitnahmeStart
	err := row.Scan(
		&i.ID,
		&i.RennenNummer,
		&i.StartNummer,
		&i.TimeClient,
		&i.TimeServer,
		&i.MeasuredLatency,
		&i.Verarbeitet,
		&i.ClientID,
		&i.Seq,
	)
	return i, err
}

const getAllZeitnahmeStart = `-- name: GetAllZeitnahmeStart :many
SELECT id, rennen_nummer, start_nummer, time_client, time_server, measured_latency, verarbeitet, client_id, seq FROM zeitnahme_start
ORDER BY id ASC
`

func (q *Queries) GetAllZeitnahmeStart(ctx context.Context) ([]ZeitnahmeStart, error) {
	rows, err := q.db.Query(ctx, getAllZeitnahmeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZeitnahmeStart{}
	for rows.Next() {
		var i ZeitnahmeStart
		if err := rows.Scan(
			&i.ID,
			&i.RennenNummer,
			&i.StartNummer,
			&i.TimeClient,
			&i.TimeServer,
			&i.MeasuredLatency,
			&i.Verarbeitet,
			&i.ClientID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenStarts = `-- name: GetOpenStarts :many
SELECT id, rennen_nummer, start_nummer, time_client, time_server, measured_latency, verarbeitet, client_id, seq FROM zeitnahme_start
WHERE verarbeitet = false
ORDER BY id ASC
`

func (q *Queries) GetOpenStarts(ctx context.Context) ([]ZeitnahmeStart, error) {
	rows, err := q.db.Query(ctx, getOpenStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZeitnahmeStart{}
	for rows.Next() {
		var i ZeitnahmeStart
		if err := rows.Scan(
			&i.ID,
			&i.RennenNummer,
			&i.StartNummer,
			&i.TimeClient,
			&i.TimeServer,
			&i.MeasuredLatency,
			&i.Verarbeitet,
			&i.ClientID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZeitnahmeStart = `-- name: GetZeitnahmeStart :one
SELECT id, rennen_nummer, start_nummer, time_client, time_server, measured_latency, verarbeitet, client_id, seq FROM zeitnahme_start
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetZeitnahmeStart(ctx context.Context, id int32) (ZeitnahmeStart, error) {
	row := q.db.QueryRow(ctx, getZeitnahmeStart, id)
	var i ZeitnahmeStart
	err := row.Scan(
		&i.ID,
		&i.RennenNummer,
		&i.StartNummer,
		&i.TimeClient,
		&i.TimeServer,
		&i.MeasuredLatency,
		&i.Verarbeitet,
		&i.ClientID,
		&i.Seq,
	)
	return i, err
}

const setZeitnahmeStartVerarbeitet = `-- name: SetZeitnahmeStartVerarbeitet :exec
UPDATE zeitnahme_start
SET verarbeitet = true
WHERE id = $1
`

func (q *Queries) SetZeitnahmeStartVerarbeitet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setZeitnahmeStartVerarbeitet, id)
	return err
}
